name: tarball-build

on:
  push:
    branches:
      - main
      - rpm-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run Makefile
        run: make netscripts.tar.xz
      - uses: actions/upload-artifact@master
        with:
          name: netscripts.tar.xz
          path: netscripts.tar.xz
